plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "ParchmentMC"
                url = "https://maven.parchmentmc.org"
            }
        }
        filter {
            includeGroupAndSubgroups("org.parchmentmc")
        }
    }
}

dependencies {
    minecraft(libs.minecraft)
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment(libs.parchment.loom)
    })
    compileOnly(project(":common")) {
        transitive = false
    }

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modCompileOnly(libs.modmenu) {
        transitive = false
    }
    modRuntimeOnly(libs.modmenu) {
        transitive = false
    }

    modImplementation(libs.accessories.fabric)
    modImplementation(libs.dependency.injection)

    include(libs.dependency.injection)
    modImplementation(libs.owo.fabric)
    //implementation("org.reflections:reflections:0.10.2")
    // TODO - Is there a particular reason why I need to include both of these on Fabric, but only reflections on NeoForge?
    include("org.reflections:reflections:0.10.2")
    include("org.javassist:javassist:3.28.0-GA")
    include(libs.yumi.mc.foundation)
}

loom {
    mods {
        "${mod_id}" {
            // Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }

    def awFile = project.file("src/main/resources/${mod_id}.accesswidener")
    if (awFile.exists()) {
        accessWidenerPath.set(awFile)
    }

    mixin {
        useLegacyMixinAp = false
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc).configure {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
}