plugins {
    id 'net.neoforged.moddev'
}

// Vanilla depends on ASM 9.3, MDG makes that a 'strict' version constraint,
// but Mixin and MixinExtras needs newer ASM so we override that here.
configurations.configureEach {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == libs.asm.core.get().group) {
            details.useVersion(libs.versions.asm.get())
            details.because("Mixin requires new ASM")
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly(libs.bundles.asm)
    compileOnly(libs.mixin)
    compileOnly(libs.mixin.extras)
    compileOnly(libs.endec)
    annotationProcessor(libs.mixin.extras)
}

neoForge {
    neoFormVersion = libs.versions.neoform.get()

    parchment {
        minecraftVersion = libs.versions.minecraft.get()
        mappingsVersion = libs.versions.parchment.get()
    }

    def atFile = file("src/main/resources/META-INF/accesstransformer.cfg")
    if (atFile.exists()) {
        accessTransformers {
            from atFile
            publish atFile
        }
    }

    validateAccessTransformers.set(true)
}